stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --no-restore
  artifacts:
    paths:
      - "**/bin/"
      - "**/obj/"
    expire_in: 1 hour
  only:
    - develop
    - production

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet test --no-build
  only:
    - develop
    - production

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up --build -d
  only:
    - production
  tags:
    - self-hosted