// <auto-generated />
using System;
using KyrgyzTest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KyrgyzTest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416104610_AddSecurityFieldsToComputer")]
    partial class AddSecurityFieldsToComputer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KyrgyzTest.Core.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("KyrgyzTest.Core.Entities.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceSecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMainPool")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastIpAddress")
                        .HasColumnType("text");

                    b.Property<int?>("StationNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb210115-f973-4a51-8669-58fd26ee043b"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7460),
                            StationNumber = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a636c34c-b97f-4a7e-8c93-cabc2f9b5e7b"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7460),
                            StationNumber = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("07767f6d-5fae-48c9-9b85-5cd8e6fab741"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7470),
                            StationNumber = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c7206f87-3fed-4a10-b4af-0e8b077d0af4"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7470),
                            StationNumber = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("db8c41ed-a631-49ee-ae05-29cf8d6c1f1b"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7470),
                            StationNumber = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8d0edf00-bc83-427f-a0e9-8576fe2c0d2e"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7480),
                            StationNumber = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("af5a11de-ad4b-4dc1-8e53-7c7c026751ee"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7480),
                            StationNumber = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bca6ca12-f958-4fe2-953c-dc4f39874d1a"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7490),
                            StationNumber = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8abe891b-5cd4-46f6-83bd-e66a0571344e"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7490),
                            StationNumber = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e2d2f647-3d02-4ece-ab77-de07340e9dcd"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7490),
                            StationNumber = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2af02d70-f150-49fc-8d00-65c68c308e64"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7500),
                            StationNumber = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eb900a1f-11a8-4889-aa70-8a600c3b97c4"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7500),
                            StationNumber = 12,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0c272dc1-1dc6-4bfc-9338-beb806548184"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7500),
                            StationNumber = 13,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("05481edc-1e2c-4700-a086-18dfea8acf6b"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7510),
                            StationNumber = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c04a49fd-24fd-4bc0-931a-e3283a6c49f7"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7510),
                            StationNumber = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("403979bd-4aaa-4d5d-9e56-9a644f3a55b5"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7510),
                            StationNumber = 16,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5a6ef0fc-e215-43eb-a8a0-fad391b2b1a4"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7520),
                            StationNumber = 17,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ff1d34df-9ae6-4eae-9a63-80a0930c565a"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7520),
                            StationNumber = 18,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bffa810e-5db6-44e0-b41d-27b325efcdb8"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7520),
                            StationNumber = 19,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5d947698-16f1-4aed-a73c-d370346a1435"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7530),
                            StationNumber = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("63021852-f379-48fd-8f14-1a610b4dd8dc"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7530),
                            StationNumber = 21,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2920255a-dfd8-4248-b937-da1fc4d6f687"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7530),
                            StationNumber = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8c4b37d3-75b0-4879-a775-d241892516c6"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7540),
                            StationNumber = 23,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("00c1d166-44f9-446b-bf2d-702d46843634"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7540),
                            StationNumber = 24,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("864fda37-c77d-4ac1-b50d-2b7aa6372eb1"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7550),
                            StationNumber = 25,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e5643ca7-1082-4d82-8f8f-94234ab8311a"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7550),
                            StationNumber = 26,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22440ce4-ea15-4c94-84ad-5343255cff1b"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7550),
                            StationNumber = 27,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ecd06967-041d-472d-b39d-aba994686ff7"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7560),
                            StationNumber = 28,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("91d800ef-15f6-45ab-93b1-3f795bb75838"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7560),
                            StationNumber = 29,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("24babd9d-f88c-495a-acbc-3ef015c391ad"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7560),
                            StationNumber = 30,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("41722276-13ce-43da-9f35-eae1d09859b5"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7570),
                            StationNumber = 31,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3bb10183-e43f-4dcb-83b1-7444fb96767b"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7570),
                            StationNumber = 32,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8a7e7bde-6b5c-4439-b8e6-aeb31abb0b28"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7570),
                            StationNumber = 33,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("faf5afdb-c04b-4b55-8674-9de25438ddbc"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7580),
                            StationNumber = 34,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8fc79fb9-90aa-4392-ad95-eaae70c09467"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7580),
                            StationNumber = 35,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4f687bde-54db-4189-8efe-837f0f12faef"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7580),
                            StationNumber = 36,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("32da59f8-ed4e-49cc-90c5-25e491654157"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7590),
                            StationNumber = 37,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("97e4fc02-465e-4e39-ae4f-41932cd9f80e"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7590),
                            StationNumber = 38,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0b2b0d70-fb63-4992-8f9c-afcaeca60fa8"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7590),
                            StationNumber = 39,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("82fb6a8a-fb92-4a14-980c-54ec7d604de7"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7600),
                            StationNumber = 40,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("382f097f-e97f-4d8b-81c9-1809bd95ccd8"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7600),
                            StationNumber = 41,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("107eba04-bb01-4ab6-9be6-9b4efd869e6f"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7600),
                            StationNumber = 42,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("de65d5b7-e6ca-4154-91e0-10b4317b5d60"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7610),
                            StationNumber = 43,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("471047e7-7d5c-479e-86ad-091a93094eda"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7610),
                            StationNumber = 44,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("67342984-8b0a-4095-a75f-5655f8dce992"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7610),
                            StationNumber = 45,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8fcf5eae-8d8c-42f8-b052-942be81b6df2"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7620),
                            StationNumber = 46,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("63a66dbf-7ed2-4333-b546-a5a68dd870ab"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7620),
                            StationNumber = 47,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("786bd44a-15a8-4dd2-8533-b8fa46fee4a3"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7620),
                            StationNumber = 48,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dd677986-c1f2-4368-bc88-3fec3fe344e8"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7630),
                            StationNumber = 49,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b28f36eb-7f14-4ccc-9387-383b343c7fa4"),
                            DeviceId = "",
                            DeviceSecretHash = "",
                            IsMainPool = false,
                            IsTrusted = false,
                            LastHeartbeat = new DateTime(2026, 4, 16, 10, 46, 10, 255, DateTimeKind.Utc).AddTicks(7630),
                            StationNumber = 50,
                            Status = 0
                        });
                });

            modelBuilder.Entity("KyrgyzTest.Core.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
