// <auto-generated />
using System;
using KyrgyzTest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KyrgyzTest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KyrgyzTest.Core.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("KyrgyzTest.Core.Entities.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StationNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Computers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("48530fb0-b06f-45dc-a0c0-1ce5c9427c36"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3710),
                            StationNumber = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9e5a5735-f7bd-4883-aeb8-6eb08c2d289f"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3710),
                            StationNumber = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cef15816-d11a-43a3-afa6-012e560386f3"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3720),
                            StationNumber = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ea84578d-6c5f-4cf1-b510-109ee40eeafb"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3720),
                            StationNumber = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a523cff8-3967-4d08-969b-8f4b5a1ac088"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3730),
                            StationNumber = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b3f2cfeb-c6fc-485c-a6de-fcca0382de84"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3730),
                            StationNumber = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b0fb4ae7-da42-425d-85ce-8a02ccddf35b"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3740),
                            StationNumber = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7d449d40-67c5-4d67-8201-ccf2b595b554"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3740),
                            StationNumber = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e226fd0a-efcd-4aca-b3c5-982a94312752"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3740),
                            StationNumber = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6b117c0d-c818-4aec-96a0-a0318f8fabc9"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3750),
                            StationNumber = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("40ff5319-f529-4458-98d3-be1cd06c3925"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3750),
                            StationNumber = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bb69c071-9e72-46c2-8623-7a1fb6372bd3"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3760),
                            StationNumber = 12,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8da6a542-036e-4c86-9a63-30ea9aa42e6a"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3760),
                            StationNumber = 13,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3159a778-e840-4e9d-a561-e5ec52154fae"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3770),
                            StationNumber = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b2cdd43b-7285-4e40-8fba-3d631f78c9bf"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3770),
                            StationNumber = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9b33c93b-d47b-441a-ad9a-0a3db6c6d6d1"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3770),
                            StationNumber = 16,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a98f4b3d-160b-4be5-8666-d5fafb463671"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3780),
                            StationNumber = 17,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0894d936-3f7c-4337-a8e6-236185e7212b"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3780),
                            StationNumber = 18,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6de178e6-2209-43ab-9494-e966d8e8acf9"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3790),
                            StationNumber = 19,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("09bf6a62-7543-4460-8c63-bd5eea2e1d4f"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3790),
                            StationNumber = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8b7b62dd-8d67-47a4-914b-39101d16a3e4"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3790),
                            StationNumber = 21,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6e97b051-2e3a-4341-b595-74dc1ae85300"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3800),
                            StationNumber = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1b0b37e1-b3ef-4d63-86aa-fcc70065bf67"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3800),
                            StationNumber = 23,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("85b2107c-1902-4bd2-811a-c4746ac20584"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3810),
                            StationNumber = 24,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f25ee7d5-fe6d-4c67-9daf-1aad69164910"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3810),
                            StationNumber = 25,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eac3e130-f79f-4d39-879e-8ee8bc085676"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3810),
                            StationNumber = 26,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a456e769-2ab9-4784-8c25-18e654cbc545"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3820),
                            StationNumber = 27,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b59a5a81-a726-415a-b9cd-71a8485a865f"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3830),
                            StationNumber = 28,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d0cfe79b-e94d-4e01-8c2a-fe0aeb2d185c"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3830),
                            StationNumber = 29,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b15cec1a-7065-4e25-8a55-6bdb24d57257"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3830),
                            StationNumber = 30,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("486ef804-3780-4f79-81e8-e307e02d0788"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3840),
                            StationNumber = 31,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bf496b19-41ff-4c69-8c2c-5e94fdf19255"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3840),
                            StationNumber = 32,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e4ca973f-d656-4e70-9dd5-2f5d6befa84d"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3850),
                            StationNumber = 33,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("73b800d9-802b-470e-ab50-3adc5c0c5c1f"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3850),
                            StationNumber = 34,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("119c3af1-0e4a-473e-bc03-7cd535b8ced3"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3850),
                            StationNumber = 35,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ecbbbd5d-9ace-4f9e-a94e-dbfca26b0e1b"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3860),
                            StationNumber = 36,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1bcf3b03-d107-4a96-9124-f8462f8f64bc"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3860),
                            StationNumber = 37,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e0ea45ab-2a0f-486a-8c11-c51d28f5bcba"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3870),
                            StationNumber = 38,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c370a9ed-df45-4cb8-ba12-945bbf885d13"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3870),
                            StationNumber = 39,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c650e9ae-45bb-4b7f-a8c1-3aa0257295f3"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3870),
                            StationNumber = 40,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("98321269-30df-4ca8-b9a3-2d435635a4be"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3880),
                            StationNumber = 41,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5f8b02ae-1b85-4e27-9b81-c9c9d23e40d6"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3880),
                            StationNumber = 42,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("174054f7-1964-4992-a672-87b0c1ac54a2"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3890),
                            StationNumber = 43,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("fe1a9d8a-80c3-476f-8306-f0afbcb33a3b"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3890),
                            StationNumber = 44,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("af4e0403-fb86-41c0-b67a-8bb5bb1be40f"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3890),
                            StationNumber = 45,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("53c365ce-63d3-4745-a899-5f51557e0ab0"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3900),
                            StationNumber = 46,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("25cd2d26-b39b-4ada-ac15-64d3116b8af3"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3900),
                            StationNumber = 47,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eb713330-dfde-43d0-80a1-6387f2b2f53b"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3910),
                            StationNumber = 48,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("892feff9-8f1c-424f-9a32-24f031cecffc"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3910),
                            StationNumber = 49,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("98a56a6d-611f-4181-8da2-895085f6ca51"),
                            LastHeartbeat = new DateTime(2026, 4, 2, 21, 28, 48, 775, DateTimeKind.Utc).AddTicks(3910),
                            StationNumber = 50,
                            Status = 0
                        });
                });

            modelBuilder.Entity("KyrgyzTest.Core.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StationNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
